version: '2'
services:
  redis:
    restart: always
    image: library/redis:latest
    ports:
      - 6379:6379
  angels-server:
    restart: always
    build:
      context: '..'
      dockerfile: ./conf/Server/Dockerfile
    container_name: angels-server
    ports:
      - 8000:8000
  angels-client:
    build:
      context: '..'
      dockerfile: ./conf/Godot/Dockerfile
    container_name: angels-client
    ports:
      - 8090:80