version: '2'
services:
  angels-redis:
    restart: always
    hostname: redis
    image: library/redis:latest
    container_name: angels_redis
    ports:
      - ${REDIS_PORT}:6379
  angels-server:
    restart: always
    build:
      context: '../..'
      dockerfile: ./conf/Server/Dockerfile.prod
    container_name: angels-server-prod
    env_file:
      - ../Server/prod_env.sh
    ports:
      - ${SERVER_PORT}:8000
  angels-client:
    build:
      context: '../..'
      dockerfile: ./conf/Godot/Dockerfile
    container_name: angels-client
    ports:
      - ${CLIENT_PORT}:80